[colors]
cursor                            = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor                    = { text = "CellBackground", cursor = "CellForeground" }
line_indicator                    = { foreground = "None", background = "None" }
footer_bar                        = { foreground = "#181818", background = "#D8D8D8" }
selection                         = { text = "CellBackground", background = "CellForeground" }
indexed_colors                    = []
transparent_background_colors     = false
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground        = "#D8D8D8"
background        = "#000000"
dim_foreground    = "#828482"
bright_foreground = "#E0E0E0"

[colors.search]
matches       = { foreground = "#181818", background = "#D8D8D8" }
focused_match = { foreground = "#181818", background = "#467AFF" }

[colors.hints]
start = { foreground = "#181818", background = "#D8D8D8" }
end   = { foreground = "#181818", background = "#467AFF" }

[colors.normal]
black   = "#181818"
white   = "#D8D8D8"
red     = "#F70135"
green   = "#39DD14"
blue    = "#467AFF"
yellow  = "#FFC422"
magenta = "#EA00FF"
cyan    = "#4BF0FC"

[colors.bright]
black   = "#6B6B6B"
white   = "#FBFFFF"
red     = "#FF5050"
green   = "#50D050"
blue    = "#8080FF"
yellow  = "#C4C417"
magenta = "#CF3FCF"
cyan    = "#02D0D0"

[colors.dim]
black   = "#0F0F0F"
white   = "#8E8E8E"
red     = "#3F0000"
green   = "#003F00"
blue    = "#00003F"
yellow  = "#FDCC0D"
magenta = "#704D68"
cyan    = "#4D7770"
