[colors]
indexed_colors                    = []
transparent_background_colors     = false
draw_bold_text_with_bright_colors = true

[colors.cursor]
text   = "CellBackground"
cursor = "CellForeground"

[colors.footer_bar]
foreground = "#BAC2DE"
background = "#6C7086"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.hints]
start = { foreground = "#313244", background = "#F5E0DC" }
end   = { foreground = "#313244", background = "#F2CDCD" }

[colors.selection]
text       = "CellBackground"
background = "CellForeground"

[colors.search]
matches       = { foreground = "#313244", background = "#9399B2" }
focused_match = { foreground = "#313244", background = "#F5E0DC" }

[colors.vi_mode_cursor]
text   = "CellBackground"
cursor = "CellForeground"

[colors.primary]
foreground        = "#CDD6F4"
background        = "#1E1E2E"
dim_foreground    = "#181825"
bright_foreground = "#BAC2DE"

[colors.normal]
black   = "#11111B"
white   = "#A6ADC8"
red     = "#F38BA8"
green   = "#A6E3A1"
blue    = "#89B4FA"
yellow  = "#F9E2AF"
magenta = "#CBA6F7"
cyan    = "#94E2D5"

[colors.bright]
black   = "#313244"
white   = "#BAC2DE"
red     = "#EBA0AC"
green   = "#A6E3A1"
blue    = "#74C7EC"
yellow  = "#F9E2AF"
magenta = "#B4BEFE"
cyan    = "#89DCEB"
