[hints]
alphabet = "12345678901bcdefghijklmnopqrstuvwxyz"

[[hints.enabled]]
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|go‐pher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
hyperlinks      = true
post_processing = true
persist         = false
command         = "xdg-open"
mouse           = { mods = "None", enabled = true }
binding         = { key = "O", mods = "Control|Shift" }

[[hints.enabled]]
regex           = "#?[a-fA-F0-9]+"
hyperlinks      = true
post_processing = true
persist         = false
action          = "Select"
mouse           = { mods = "None", enabled = true }
binding         = { key = "S", mods = "Control|Shift" }
